<?php

use Illuminate\Support\Facades\DB;

return new class {
	public function run(){
		$abilities = [
			[
				"ability"=>"view-document-templates",
				"role_title"=>"admin"
			],
			[
				"ability"=>"view-user-invoice-client",
				"role_title"=>"user"
			],
			[
				"ability"=>"add-invoice-client",
				"role_title"=>"user"
			],
			[
				"ability"=>"update-invoice-client",
				"role_title"=>"user"
			],
			[
				"ability"=>"delete-user-invoice-client",
				"role_title"=>"user"
			],
			[
				"ability"=>"view-user-invoice-product",
				"role_title"=>"user"
			],
			[
				"ability"=>"add-user-invoice-product",
				"role_title"=>"user"
			],
			[
				"ability"=>"update-user-invoice-product",
				"role_title"=>"user"
			],
			[
				"ability"=>"delete-user-invoice-product",
				"role_title"=>"user"
			],
			[
				"ability"=>"view-user-invoice-expense",
				"role_title"=>"user"
			],
			[
				"ability"=>"add-user-invoice-expense",
				"role_title"=>"user"
			],
			[
				"ability"=>"update-user-invoice-expense",
				"role_title"=>"user"
			],
			[
				"ability"=>"delete-user-invoice-expense",
				"role_title"=>"user"
			],
			[
				"ability"=>"view-user-invoice-expense-category",
				"role_title"=>"user"
			],
			[
				"ability"=>"add-user-invoice-expense-category",
				"role_title"=>"user"
			],
			[
				"ability"=>"update-user-invoice-expense-category",
				"role_title"=>"user"
			],
			[
				"ability"=>"delete-user-invoice-expense-category",
				"role_title"=>"user"
			],
			[
				"ability"=>"view-user-invoice-business",
				"role_title"=>"user"
			],
			[
				"ability"=>"add-user-invoice-business",
				"role_title"=>"user"
			],
			[
				"ability"=>"update-user-invoice-business",
				"role_title"=>"user"
			],
			[
				"ability"=>"delete-user-invoice-business",
				"role_title"=>"user"
			],
			[
				"ability"=>"view-user-invoice",
				"role_title"=>"user"
			],
			[
				"ability"=>"add-user-invoice",
				"role_title"=>"user"
			],
			[
				"ability"=>"update-user-invoice",
				"role_title"=>"user"
			],
			[
				"ability"=>"delete-user-invoice",
				"role_title"=>"user"
			],
			[
				"ability"=>"view-user-invoice-proposal",
				"role_title"=>"user"
			],
			[
				"ability"=>"add-user-invoice-proposal",
				"role_title"=>"user"
			],
			[
				"ability"=>"update-user-invoice-proposal",
				"role_title"=>"user"
			],
			[
				"ability"=>"delete-user-invoice-proposal",
				"role_title"=>"user"
			],
			[
				"ability"=>"view-user-invoice-delivery-note",
				"role_title"=>"user"
			],
			[
				"ability"=>"add-user-invoice-delivery-note",
				"role_title"=>"user"
			],
			[
				"ability"=>"update-user-invoice-delivery-note",
				"role_title"=>"user"
			],
			[
				"ability"=>"delete-user-invoice-delivery-note",
				"role_title"=>"user"
			],
			[
				"ability"=>"copy-user-invoice-document",
				"role_title"=>"user"
			],
			[
				"ability"=>"add-user-invoice-document-payment",
				"role_title"=>"user"
			],
			[
				"ability"=>"delete-user-invoice-document-payment",
				"role_title"=>"user"
			],
			[
				"ability"=>"email-user-invoice-document",
				"role_title"=>"user"
			],
			[
				"ability"=>"use-document-template",
				"role_title"=>"user"
			],
			[
				"ability"=>"manage-custom-field",
				"role_title"=>"user"
			],
			[
				"ability"=>"manage-user-document-templates",
				"role_title"=>"user"
			]
		];
		DB::table("abilities")->insert($abilities);
	}
}

?>